[server]
# Use the container hostname
use-ipv4=yes
use-ipv6=no
# Allow name resolution for .local
allow-interfaces=eth0
# Intentionally disable TTL check (default Avahi posture -- this is the vuln)
check-response-ttl=no
# Don't restrict published records
allow-point-to-point=yes

[wide-area]
enable-wide-area=no

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes
# Publish some services so there's something to attack
add-service-cookie=yes

[reflector]
enable-reflector=no

[rlimits]
